services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    ports:
      - "9999:8080"
    networks:
      - rdf-network
    volumes:
      - blazegraph_data:/var/lib/blazegraph

  rdf4j:
    image: eclipse/rdf4j-workbench:5.0.1
    container_name: rdf4j
    ports:
      - "8082:8080"
    depends_on:
      - blazegraph
    networks:
      - rdf-network

  refine:
    image: ontotext/refine
    restart: unless-stopped
    ports:
      - "7333:7333"
    volumes:
      - refine_data:/opt/ontorefine/data
    networks:
      - rdf-network

  webvowl:
    image: webvowl:v1
    container_name: webvowl
    ports:
      - "8083:8080"
    networks:
      - rdf-network

networks:
  rdf-network:

volumes:
  blazegraph_data:
  refine_data:

