services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    ports:
      - "9999:8080"
    networks:
      - monorepo_default
    volumes:
      - blazegraph_data:/var/lib/blazegraph
      - ./data:/data

  rdf4j:
    image: eclipse/rdf4j-workbench:5.0.1
    container_name: rdf4j
    ports:
      - "8082:8080"
    depends_on:
      - blazegraph
    networks:
      - monorepo_default

  ontorefine:
    image: ontotext/refine
    container_name: ontorefine
    restart: unless-stopped
    ports:
      - "7333:7333"
    volumes:
      - refine_data:/opt/ontorefine/data
    networks:
      - monorepo_default

  openrefine:
    image: easypi/openrefine
    ports:
      - "3333:3333"
    volumes:
      - openrefine_data:/data
    environment:
      - REFINE_INTERFACE=0.0.0.0
      - REFINE_PORT=3333
      - REFINE_MIN_MEMORY=1024M
      - REFINE_MEMORY=1024M
      - REFINE_DATA_DIR=/data
      - REFINE_EXTRA_OPTS=refine.headless=true
    restart: unless-stopped
    networks:
      - monorepo_default

  webvowl:
    image: metacodingio/webvowl:v1
    container_name: webvowl
    ports:
      - "8083:8080"
    networks:
      - monorepo_default

  trifid:
    image: ghcr.io/zazuko/trifid:latest
    container_name: trifid
    ports:
      - "8084:8080"
    environment:
      - SPARQL_ENDPOINT_URL=http://blazegraph:8080/bigdata/namespace/kb/sparql
      - SPARQL_USERNAME=admin
      - SPARQL_PASSWORD=admin
    networks:
      - monorepo_default

  blueprint:
    image: ghcr.io/zazuko/blueprint:latest
    container_name: blueprint
    ports:
      - "8085:80"
    environment:
      - ENDPOINT_URL=http://0.0.0.0:8084/query
      # - SPARQL_CONSOLE_URL=http://trifid:8080/sparql
      # - GRAPH_EXPLORER_URL=http://trifid:8080/graph-explorer
    networks:
      - monorepo_default

networks:
  monorepo_default:
    external: true

volumes:
  blazegraph_data:
  refine_data:
  openrefine_data:
